name: Setup clasp

on: [push]

jobs:
  setup-clasp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install clasp
        run: npm install -g @google/clasp
      - name: Create .clasp.json
        run: |
          echo '{
            "scriptId": "'${{ secrets.CLASP_SCRIPT_ID }}'",
            "rootDir": "./"
          }' > .clasp.json
      - name: Push to Google Apps Script
        run: clasp push
