#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Ejecuta lint-staged y captura el código de salida
npx lint-staged
exit_code=$?

# Si lint-staged falla, imprime un mensaje y termina con un código de error
if [ $exit_code -ne 0 ]; then
  echo "lint-staged falló con el código de salida $exit_code"
  exit $exit_code
fi
