name: Setup clasp

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      rollback:
        description: 'Rollback to previous commit'
        required: false
        type: boolean

jobs:
  setup-clasp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install clasp
        run: npm install -g @google/clasp
      - name: Set up .clasprc.json
        run: |
          echo '${{ secrets.CLASP_TOKEN }}' > ~/.clasprc.json
      - name: Create .clasp.json
        run: |
          echo '{
            "scriptId": "'${{ secrets.CLASP_SCRIPT_ID }}'",
            "rootDir": "./"
          }' > .clasp.json
      - name: Verify .claspignore
        run: |
          cat .claspignore
      - name: Push to Google Apps Script
        run: clasp push

  rollback:
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.rollback == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install CLASP
        run: npm install -g @google/clasp

      - name: Authenticate with CLASP
        run: |
          echo '${{ secrets.CLASP_TOKEN }}' > ~/.clasprc.json

      - name: Rollback to previous commit
        run: |
          echo "Current directory: $(pwd)"
          echo "Git status:"
          git status
          echo "Checking out previous commit..."
          git checkout HEAD^1
          echo "Git status after checkout:"
          git status
          echo "Creating .clasp.json..."
          echo '{
            "scriptId": "${{ secrets.CLASP_SCRIPT_ID }}",
            "rootDir": "./"
          }' > .clasp.json
          echo "Contents of .clasp.json:"
          cat .clasp.json
          echo "Pushing to CLASP..."
          clasp push -f
        continue-on-error: true

      - name: List files
        run: ls -la

      - name: Check CLASP version
        run: clasp -v

      - name: Notify rollback completion
        run: |
          echo "Rollback process completed. Check logs for details."
