name: Setup clasp

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      rollback:
        description: 'Rollback to previous commit'
        required: false
        type: boolean

jobs:
  setup-clasp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install clasp
        run: npm install -g @google/clasp
      - name: Set up .clasprc.json
        run: |
          echo '${{ secrets.CLASP_TOKEN }}' > ~/.clasprc.json
      - name: Create .clasp.json
        run: |
          echo '{
            "scriptId": "'${{ secrets.CLASP_SCRIPT_ID }}'",
            "rootDir": "./"
          }' > .clasp.json
      - name: Verify .claspignore
        run: |
          cat .claspignore
      - name: Push to Google Apps Script
        run: clasp push

  rollback:
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.rollback == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install CLASP
        run: npm install -g @google/clasp

      - name: Authenticate with CLASP
        run: |
          echo '${{ secrets.CLASP_TOKEN }}' > ~/.clasprc.json

      - name: Rollback to previous commit
        run: |
          git checkout HEAD^1
          clasp push -f

      - name: Notify rollback completion
        run: |
          echo "Rollback completed successfully!"
