name: Setup clasp

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      rollback:
        description: 'Rollback to previous commit'
        required: false
        type: boolean

jobs:
  setup-clasp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install clasp
        run: npm install -g @google/clasp
      - name: Set up .clasprc.json
        run: |
          echo '${{ secrets.CLASP_TOKEN }}' > ~/.clasprc.json
      - name: Create .clasp.json
        run: |
          echo '{
            "scriptId": "'${{ secrets.CLASP_SCRIPT_ID }}'",
            "rootDir": "./"
          }' > .clasp.json
      - name: Verify .claspignore
        run: |
          cat .claspignore
      - name: Push to Google Apps Script
        run: clasp push

  rollback:
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.rollback == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
  
      - name: Install CLASP
        run: npm install -g @google/clasp
  
      - name: Authenticate with CLASP
        run: |
          echo '${{ secrets.CLASP_TOKEN }}' > ~/.clasprc.json
  
      - name: Create rollback branch with commit message
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Get the previous commit hash
          PREV_COMMIT=$(git rev-parse HEAD^)
          
          # Get the commit message of the previous commit
          COMMIT_MSG=$(git log --format=%B -n 1 $PREV_COMMIT | sed -e 's/[^A-Za-z0-9._-]/_/g' | cut -c1-50)
          
          # Create a branch name with date and commit message
          BRANCH_NAME="rollback-$(date +%Y%m%d-%H%M%S)-${COMMIT_MSG}"
          
          # Create and push the new branch
          git checkout -b $BRANCH_NAME $PREV_COMMIT
          git push origin $BRANCH_NAME
          
          echo "Created and pushed branch: $BRANCH_NAME"
  
      - name: Rollback to previous commit
        run: |
          echo "Current directory: $(pwd)"
          echo "Git status:"
          git status
          echo "Creating .clasp.json..."
          echo '{
            "scriptId": "${{ secrets.CLASP_SCRIPT_ID }}",
            "rootDir": "./"
          }' > .clasp.json
          echo "Contents of .clasp.json:"
          cat .clasp.json
          echo "Pushing to CLASP..."
          clasp push -f
        continue-on-error: true
  
      - name: List files
        run: ls -la
  
      - name: Check CLASP version
        run: clasp -v
  
      - name: Notify rollback completion
        run: |
          echo "Rollback process completed. Check logs for details."